### ISSUE TITLE
Decide on further visualization types

### ISSUE THREAD

**Issue by FWirtz** [openHPI/m.e.i.n.e.l#11]
ideas:
- [x] GitHub Stats like heatmap (see #14 )
- [x] spinner
- [x] more standard plotly elements
- [x] line graph that allows toggeling on/off specific lines

**Comment by MaximilianV** [comment]
@FWirtz what is a spinner?
Did you mean the circular progress? If so, we can close this issue :)

**Comment by FWirtz** [comment]
Yeah, I guess I meant that haha :+1:
